# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import os
#import sys
#sys.path.insert(0, os.path.abspath('.'))

from sphinx.highlighting import lexers
from pygments.lexers.web import PhpLexer

on_rtd = os.environ.get('READTHEDOCS') == 'True'
on_circleci = os.environ.get('CIRCLECI') == 'true'
on_github = ('GITHUB_REF' in os.environ)

if on_rtd:
    rtd_project = os.environ.get('READTHEDOCS_PROJECT')
    rtd_version = os.environ.get('READTHEDOCS_VERSION')
    rtd_language = os.environ.get('READTHEDOCS_LANGUAGE')
    api_url_base = 'https://%s.sourceforge.io/docs/%s/api/' % (rtd_project, rtd_version)
elif on_circleci:
    ci_branch =  os.environ.get('CIRCLE_BRANCH')
    api_url_base = '/docs/%s/api/' % ci_branch
elif on_github:
    gh_ref = os.environ.get('GITHUB_REF')
    gh_repo = os.environ.get('GITHUB_REPOSITORY')
    gh_owner, gh_proj = gh_repo.split('/')
    if gh_ref.startswith('refs/heads/'):
        gh_subdir = gh_ref.split('/')[-1]
    elif gh_ref.startswith('refs/tags/'):
        gh_subdir = '.'.join(gh_ref.split('/')[-1].split('.')[0:2])
    else:
        gh_subdir = 'tmp'
    api_url_base = '/%s/docs/%s/api/' % (gh_proj, gh_subdir)
else:
    api_url_base = '/api/'

# enable highlighting for PHP code not between ``<?php ... ?>`` by default
lexers['php'] = PhpLexer(startinline=True)
lexers['php-annotations'] = PhpLexer(startinline=True)
lexers['php-standalone'] = PhpLexer(startinline=True)

# use PHP as primary domain
primary_domain = 'php'
highlight_language ='php'

api_url = api_url_base + '%s'

# -- Project information -----------------------------------------------------

project = 'PHPUnit Extensions'
copyright = '2020, Paweł Tomulik'
author = 'Paweł Tomulik'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.intersphinx',
    'sensio.sphinx.php',
    'sensio.sphinx.configurationblock',
    'sensio.sphinx.phpcode',
    # 'sensio.sphinx.bestpractice',     # buggy
    'sensio.sphinx.codeblock'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['page_index.rst']


# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = { }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

html_context = {
    'css_files': [
        '_static/css/custom.css',
    ]
}

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'PHPUnitExtensionsdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'PHPUnitExtensions.tex', 'PHPUnit Extensions Documentation',
     'Paweł Tomulik', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'phpunitextensions', 'PHPUnit Extensions Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'PHPUnitExtensions', 'PHPUnit Extensions Documentation',
     author, 'PHPUnitExtensions', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}


def setup(app):
    app.add_css_file('css/custom.css')

# vim: set ts=4 sw=4 et:
