---
version: "2"
##checks:
##  argument-count:
##    config:
##      threshold: 5
patterns:
  - "packages/"
exclude_patterns:
  - ".psalm/"
  - "build/"
  - "docs/"
  - "bin/"
  - "vendor/"
  - "**/tests/"
  - "**/behat/"
  - "**/vendor/"
plugins:
  phpcodesniffer:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
          php:
            filters:
              # The traits providing assertions are all similar, by design.
              - "(Stmt_Trait ClassPropertiesEqualToTrait ___)"
              - "(Stmt_Trait ClassPropertiesIdenticalToTrait ___)"
              - "(Stmt_Trait ObjectPropertiesEqualToTrait ___)"
              - "(Stmt_Trait ObjectPropertiesIdenticalToTrait ___)"
              - "(Stmt_Trait ExtendsClassTrait ___)"
              - "(Stmt_Trait ImplementsInterfaceTrait ___)"
              - "(Stmt_Trait UsesTraitTrait ___)"
              - "(Stmt_Trait HasPregCapturesTrait ___)"

  fixme:
    enabled: true
