name: Docs Deploy

on:
  release:
    types:
      - published

jobs:
  deploy-docs:
    name: Build & Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Build API docs
        run: |
          php docker/initialize
          docker/docs run --rm sami build

      - name: Build user docs
        run: docker/docs run --rm sphinx build

      - name: Experiments
        run: |
          echo ${{ github.event.release.tag_name }}


##      - name: Deploy on gh-pages
##        uses: peaceiris/actions-gh-pages@v3.7.0-8
##        with:
##          github_token: ${{ secrets.GITHUB_TOKEN }}
##          publish_dir: ./docs/build/html
##          destination_dir: ./docs
